### ISSUE TITLE
Implementation of VBI skip

### ISSUE THREAD

**Issue by ivan89el** [Gamer64ytb/Dolphin-Enhanced#1]
Is it possible to implement on this assembly?

**Comment by Gamer64ytb** [comment]
I'll try implement it soon.

**Comment by ivan89el** [comment]
@Gamer64ytb 
Maybe this will help: https://github.com/Medard22/Dolphin-MMJR2-VBI

**Comment by Sam-Belliveau** [comment]
Hey guys, I'm the person who created VBI Skip. I'm sure it's possible to back port but you're gonna struggle. VBI Skip was a small addition to a big rewrite i did to the core timings system in dolphin. So much in dolphin has likely changed that this might be a very painful change.

**Comment by ivan89el** [comment]
@Sam-Belliveau 
Hi! I didn't know how to contact you. This is probably the fastest version of dolphin for android devices. By implementing this, you will be able to speed it up even more, this will give the highest performance on "potato" devices. I asked Medard22, but he doesn't have enough knowledge: https://github.com/Medard22/Dolphin-MMJR2-VBI/discussions/56

**Comment by CaryllSimpas** [comment]
Hello can you implement VBI skip on Dolphin Mmjr v1 11505? V1 is much smoother than mmjr v2 Im using a mediatek device that's why I can tell that v1 is good. But the problem here is the audio crackling so I hope someone will implement that hack to fix the audio crackling

**Comment by ivan89el** [comment]
@CaryllSimpas
Isn't this fork based on MMJR1 11505?

**Comment by CaryllSimpas** [comment]
We just don't know yet if gamer64 still modding this project...we can't tell if it's base apk is from v1 or v2.

**Comment by CaryllSimpas** [comment]
Until he release it.

**Comment by Gamer64ytb** [comment]
I may continue this fork as enternain purposes. But not releasing APKs for now.

**Comment by Gamer64ytb** [comment]
Hi, it's been a year, but i'm happy to inform that i'm kinda back and VBI Skip is now available

I'm putting it into releases now :smiley:
