### ISSUE TITLE
Purpose of this fork

### ISSUE THREAD

**Issue by K0bin** [Gamer64ytb/Dolphin-Enhanced#2]
What's the point of this fork?

Any useful changes should be cleaned up and upstreamed instead

**Comment by kleidiss** [comment]
@K0bin The creator was known to make useless forks , This is just one more of them , It will get probably discontinued after 3 months like his other forks

**Comment by Gamer64ytb** [comment]
A goodbye fork. I will get Steam Deck soon

**Comment by Gamer64ytb** [comment]
I Will just try port some things as custom drivers or similar for ppl Who still use MMJ.

**Comment by K0bin** [comment]
Why is a "goodbye fork" necessary? What does it bring to the table that official Dolphin doesn't have. As far as I can tell you're still just messily rebasing changes to official Dolphin. (Including the speculative EFB cache refresh I implemented)

**Comment by kleidiss** [comment]
Don't bother with this guy 
He won't bring anything new to the table , As matter of fact i'm trying to compile the APK for myself and see if it even works on Android 14

**Comment by Gamer64ytb** [comment]
Kleidis when revive on reddit or discord?

**Comment by kleidiss** [comment]
@Gamer64ytb 

Any other platform i can get in contact with you , that you actually reply on

Discord is a ghost town

**Comment by Gamer64ytb** [comment]
Telegram?

**Comment by K0bin** [comment]
> I Will just try port some things as custom drivers or similar for ppl Who still use MMJ

Fwiw I wrote the custom driver integration in Dolphin and I would strongly prefer if you didn't do that.
